// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clsyzgvqkhakntjymycc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsc3l6Z3Zxa2hha250anlteWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTQxMTUsImV4cCI6MjA1OTk3MDExNX0.lIJ_d66V7vbJAEAb9zUnWCegqXaXyd5lLT7f0xdByPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});